on: push
name: node-license-checker docker build
jobs:
  node-license-checkerIsMaster:
    name: node-license-checker is master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: node-license-checker is master
      uses: actions/bin/filter@3c98a2679187369a2116d4f311568596d3725740
      with:
        args: branch master
    - name: node-license-checker docker registry
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: node-license-checker action
      uses: docker://cdssnc/touched-github-action:latest
      with:
        args: node-license-checker/**
    - name: build node-license-checker
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: build -t cdssnc/node-license-checker-github-action ./node-license-checker
    - name: push node-license-checker
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: push cdssnc/node-license-checker-github-action
