on: push
name: docker-lint docker build
jobs:
  docker-lintIsMaster:
    name: docker-lint is master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker-lint is master
      uses: actions/bin/filter@3c98a2679187369a2116d4f311568596d3725740
      with:
        args: branch master
    - name: docker-lint docker registry
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: docker-lint action
      uses: docker://cdssnc/touched-github-action:latest
      with:
        args: docker-lint/**
    - name: build docker-lint
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: build -t cdssnc/docker-lint-github-action ./docker-lint
    - name: push docker-lint
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: push cdssnc/docker-lint-github-action
